linters:
  enable:
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - funlen
    - gci
    - goconst
    - godot
    - gofmt
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
